=== hkachhadia/WEB-DEV/16_EXP/exp16.dtd
<!ELEMENT LDRPITR (course)>
<!ELEMENT course (CE3G)>
<!ELEMENT CE3G (student+)>
<!ELEMENT student (eno,name,email,semester,result,phone,address)>
<!ELEMENT eno (#PCDATA)>
<!ELEMENT name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT result (spi,cpi)>
<!ELEMENT spi (#PCDATA)>
<!ELEMENT cpi (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST course id CDATA #REQUIRED>

=== hkachhadia/WEB-DEV/16_EXP/exp16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LDRPITR SYSTEM "exp16.dtd">
<LDRPITR>
    <course id = "BE">
    <CE3G>
    <student>
    <eno>23BECE30456</eno>
    <name>
        <fname>het</fname>
        <lname>kachhadia</lname>
    </name>
    <email>het@gmail.com</email>
    <semester>3rd</semester>
    <result>
        <spi>9.9</spi>
        <cpi>10.0</cpi>
    </result>
    <phone>1234567890</phone>
    <address>ahmedabad</address>
</student>
</CE3G>
</course>
</LDRPITR>
